apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-static-website
spec: 
  selector: 
    matchLabels:
      app: static-website
  replicas: 2
  template: 
    metadata:
      labels:
        app: static-website
    spec:
      containers:  
      - name: static-website
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts: 
          - mountPath: "/usr/local/apache2/htdocs/"
            name: html-volume
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: htmlclaim


---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  labels:
    app: static-website-service
spec:
  type: NodePort
  ports:
  - nodePort: 30500
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: static-website