---
version: '1'

services:
 mydb1:
  image: mysql:5
  environment:
   MYSQL_ROOT_PASSWORD: ******
   MYSQL_DATABASE: sample
 
 mywordpress1:
  image: wordpress
  ports:
   - 8888:80
  links:
   - mydb1:mysql
...