--- 
- 
  hosts: localhost
  name: "Install and start apache2 service"

  tasks: 
    - name: "Install apache2 service"
      apt:
        name: apache2
        state: present
        
    - name: start http service
      service:
        name: apache2
        state: started
