- name: lookup demo
  hosts: localhost
  tasks:
  - name: List variables that start with qz_
    debug: msg="{{ lookup('varnames', '^qz_.+')}}"
    vars:
      qz_1: hello
      qz_2: world
      qa_1: "I won't show"
      qz_: "I won't show either"

  - name: Show all variables
    debug: msg="{{ lookup('varnames', '.+')}}"

  - name: Show variables with 'hosts' in their names
    debug: msg="{{ lookup('varnames', 'hosts')}}"

  - name: Find several related variables that end specific way
    debug: msg="{{ lookup('varnames', '.+_zone$', '.+_location$') }}"