#Version 0.0.1

FROM ubuntu:latest

MAINTAINER Varad Ahirwadkar "varadahirwadkar36@gmail.com"

RUN apt-get update

RUN apt-get install -y nginx

RUN echo 'Hello World!' > /usr/share/nginx/html/index.html

EXPOSE 8081